version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: develop
  - package-ecosystem: cargo
    directory: "/src/util/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: develop
