[package]
name = "daemon-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librevault_util = { path = "../util" }
figment = { version = "0.10.6", features = ["json"] }
log = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
simple_logger = "1.13.0"
directories = "3.0.2"
tokio = { version = "1.12.0", features = ["rt", "macros", "rt-multi-thread", "fs", "sync", "net"] }
notify = "5.0.0-pre.13"
igd = { version = "0.12.0", features = ["aio"] }
futures = "0.3.17"
