[package]
name = "daemon-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
librevault_util = { path = "../util" }
figment = { version = "0.10.6", features = ["toml"] }
log = "0.4.14"
serde = { version = "1", features = ["derive"] }
#simple_logger = "1.13.0"
directories = "4.0.1"
tokio = { version = "1.12.0", features = ["rt", "macros", "rt-multi-thread", "fs", "sync", "net", "signal"] }
notify = "5.0.0-pre.13"
igd = { version = "0.12.0", features = ["aio"] }
futures = "0.3.17"
bytes = "1.1.0"
serde_json = "1"
tonic = "0.6.1"
prost = "0.9.0"
tonic-reflection = "0.3.0"
hex = "0.4.3"
env_logger = "0.9.0"
libp2p = "0.40.0"

[build-dependencies]
tonic-build = "0.6.0"
