/* Copyright (C) 2015 Alexander Shishenko <GamePad64@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#pragma once
#include "../P2PDirectory.h"
#include "../../Meta.h"

namespace librevault {

class AbstractParser {
public:
	enum message_type : byte {
		HANDSHAKE = 0x00,
		META_LIST = 0x01,
		META_REQUEST = 0x02,
		META = 0x03,
		BLOCK_REQUEST = 0x04,
		BLOCK = 0x05,

		// Generated by P2PDirectory itself. Must be handled differently.
		PROTOCOL_TAG = 0xFE,
		KEEP_ALIVE = 0xFF
	};

	struct Handshake {
		std::string user_agent;
		blob dir_hash;
		blob auth_token;
	};

	struct MetaList {
		std::vector<::librevault::Meta::PathRevision> revision;
	};

	struct MetaRequest {
		blob path_id;	// blob = path_id, int64_t = revision
	};

	struct Meta {
		AbstractDirectory::SignedMeta smeta;
	};

	struct BlockRequest {
		blob block_id;
	};

	struct Block {
		blob block_id;
		blob block_content;
	};

	struct parse_error : std::runtime_error {
		parse_error() : std::runtime_error("Parse error"){}
	};

	AbstractParser(){}
	virtual ~AbstractParser(){}

	blob prefix(blob&& unprefixed, message_type type);

	// gen_* messages return messages in format <length=uint32_be><type=byte><payload>
	// parse_* messages take argument in format <type=byte><payload>, without length-prefix

	virtual blob gen_handshake(const Handshake& message_struct) = 0;
	virtual Handshake parse_handshake(const blob& message_raw) = 0;

	virtual blob gen_meta_list(const MetaList& message_struct) = 0;
	virtual MetaList parse_meta_list(const blob& message_raw) = 0;

	virtual blob gen_meta_request(const MetaRequest& message_struct) = 0;
	virtual MetaRequest parse_meta_request(const blob& message_raw) = 0;

	virtual blob gen_meta(const Meta& message_struct) = 0;
	virtual Meta parse_meta(const blob& message_raw) = 0;

	virtual blob gen_block_request(const BlockRequest& message_struct) = 0;
	virtual BlockRequest parse_block_request(const blob& message_raw) = 0;

	virtual blob gen_block(const Block& message_struct) = 0;
	virtual Block parse_block(const blob& message_raw) = 0;
};

} /* namespace librevault */
